### Получение студента
GET http://localhost:8080/getStudent/0
Content-Type: application/json

### Создание студента 1
POST http://localhost:8080/addStudent
Content-Type: application/json

{
"name": "Sergey",
"lastName": "Mizorov",
"middleName": "Petrovich",
"passport": "1122 667755"
}

### Создание студента 2
POST http://localhost:8080/addStudent
Content-Type: application/json

{
"name": "Andrey",
  "lastName": "Petrov",
"middleName": "Petrovich",
  "passport": "1133 667700"
}

### Создание студента 3
POST http://localhost:8080/addStudent
Content-Type: application/json

{
  "name": "Petr",
  "lastName": "Ivanov",
  "middleName": "Petrovich",
  "passport": "1144 667777"
}

### Удаление студента 1
DELETE http://localhost:8080/deleteStudent/0
Content-Type: application/json
